# ArgoCD Blue/Green 배포 예제
apiVersion: argoproj.io/v1alpha1     # apps/v1 대신 argoproj.io/v1alpha1을 사용한다
kind: Rollout  # Deployment 대신 Rollout을 사용한다
metadata:
  name: frontend-bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-bluegreen
  template:
    metadata:
      labels:
        app: frontend-bluegreen
    spec:
      containers:
      - name: frontend-bluegreen
        image: myharbor.apps.211-34-231-93.nip.io/edu/vue_crud_security
        imagePullPolicy: Always
        env:
        - name: BACKEND_API_URL
          value: "backend" 
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: frontend
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: frontend-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP   
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
spec:
  selector:
    app: frontend-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  
