apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: edu3
  name: frontend-rollouts-active
  # annotations:
  #   kubernetes.io/ingress.class: alb
  #   alb.ingress.kubernetes.io/group.name: rollouts-test
  #   alb.ingress.kubernetes.io/scheme: internal
  #   alb.ingress.kubernetes.io/security-groups: <<<sg id>>>
  #   alb.ingress.kubernetes.io/healthcheck-path: "/"
  #   alb.ingress.kubernetes.io/certificate-arn: <<<acm arn>>>
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  #   alb.ingress.kubernetes.io/backend-protocol: HTTP
  #   alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: "frontend-rollouts-active.apps.211-34-231-93.nip.io"
      http:
        paths:
          - backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
            path: /
            pathType: Prefix
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: frontend-rollouts-preview
  # annotations:
  #   kubernetes.io/ingress.class: alb
  #   alb.ingress.kubernetes.io/group.name: rollouts-test
  #   alb.ingress.kubernetes.io/scheme: internal
  #   alb.ingress.kubernetes.io/security-groups: <<<sg id>>>
  #   alb.ingress.kubernetes.io/healthcheck-path: "/"
  #   alb.ingress.kubernetes.io/certificate-arn: <<<acm arn>>>
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  #   alb.ingress.kubernetes.io/backend-protocol: HTTP
  #   alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: "frontend-rollouts-preview.apps.211-34-231-93.nip.io"
      http:
        paths:
          - backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
            path: /
            pathType: Prefix
          - backend:
              service:
                name: frontend-preview
                port:
                  number: 80
            path: /
            pathType: Prefix
