apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-svc.yaml
images:
- name: ghcr.io/heewon00/springboot_crud_security_keycloak_new
  newTag: v2
